# Generated by Django 4.2.7 on 2023-11-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254),
        ),
    ]
